site_name: InfraKitchen
site_url: https://opensource.electrolux.one/infrakitchen/
repo_name: GitHub Repository
repo_url: https://github.com/electrolux-oss/infrakitchen
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2025 Electrolux Group

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  custom_dir: docs-overrides
  palette:
    - media: "docsprefers-color-scheme: light"
      scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "docsprefers-color-scheme: dark"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: assets/images/ik-logo.png
  favicon: assets/images/ik-logo.png
  icon:
    repo: material/github
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.integrate

nav:
  - Home: index.md
  - Getting Started:
      - Quick Start: getting-started/quick-start.md
      - What is InfraKitchen?: getting-started/overview.md
      - Development:
          - Nix Flake: getting-started/development/nix-flake.md
          - Docker: getting-started/development/docker.md
          - Podman: getting-started/development/podman.md
      - Deployment:
          - Requirements: getting-started/deployment/requirements.md
          - Docker: getting-started/deployment/image.md
          - Kubernetes: getting-started/deployment/kubernetes.md
  - User Guides:
      - Platform Engineer Guide: guides/platform-engineer-guide.md
      - Developer Guide: guides/developer-guide.md
  - Core Concepts:
      - Overview: core-concepts/overview.md
      - Templates: core-concepts/templates/overview.md
      - Executors: core-concepts/executors/overview.md
      - Resources:
          - Overview: core-concepts/resources/overview.md
          - Workflow: core-concepts/resources/workflow.md
      - Workspaces: core-concepts/workspaces/overview.md
      # - Blueprints: core-concepts/blueprints/overview.md - we do not support it yet
  - Integrations:
      - Overview: integrations/overview.md
      - Troubleshooting: integrations/troubleshooting.md
      - Git Providers:
          - Overview: integrations/git/overview.md
          - GitLab: integrations/git/gitlab.md
          - GitHub: integrations/git/github.md
          - Bitbucket: integrations/git/bitbucket.md
          - Azure DevOps: integrations/git/azure-devops.md
      - Cloud Providers:
          - Overview: integrations/cloud/overview.md
          - AWS: integrations/cloud/aws.md
          - Azure: integrations/cloud/azure.md
          - Google Cloud: integrations/cloud/gcp.md
          - MongoDB Atlas: integrations/cloud/mongodb.md
          - Datadog: integrations/cloud/datadog.md
      - Auth Providers:
          - Overview: integrations/auth/overview.md
          - GitHub: integrations/auth/github.md
          - Microsoft: integrations/auth/microsoft.md
          - Backstage: integrations/auth/backstage.md
          - Service Account: integrations/auth/service-account.md
          - Guest: integrations/auth/guest.md
  - Secrets:
      - Overview: secrets/overview.md
      - Providers:
          - AWS Secrets Manager: secrets/providers/aws.md
          - GCP Secret Manager: secrets/providers/gcp.md
          - Custom Secrets: secrets/providers/custom.md
  - Operations:
      - Kubernetes: operations/kubernetes.md
      - Activity:
          - Overview: operations/activity/overview.md
          - Audit Logs: operations/activity/audit.md
          - Execution Logs: operations/activity/logs.md
          - Revision History: operations/activity/revisions.md
      # - MCP Server: operations/mcp.md - we do not support it yet
      - Feature Flags: operations/feature_flags.md
      - Batch Operations: operations/batch_operations.md
  - Architecture: architecture.md
  - FAQ: faq.md

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      auto_title: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
      toc_depth: 2

plugins:
  - glightbox
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/electrolux-oss
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/infrakitchen
    - icon: fontawesome/brands/discord
      link: https://discord.gg/HAk7caCMf9
